### ISSUE TITLE
Mounting overlayfs error

### ISSUE THREAD

**Issue by pgaskin** [davstott/ubuntu-usb-merge#2]
```
patrick@DESKTOP:~/Documents$ sudo ./merge.sh /media/patrick/UBUNTU
```

<pre>Mounting /media/patrick/UBUNTU/casper/filesystem.squashfs
Mounting /media/patrick/UBUNTU/casper-rw
Mounting overlayfs
mount: wrong fs type, bad option, bad superblock on none,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
</pre>

**Comment by pgaskin** [comment]
I have found a solution. 
Solution:

Before running the command:

```
fsck /path/to/usb/casper-rw
```

**Comment by davstott** [comment]
Thanks for tracking that down and fixing it, I'd only just started to try to reproduce it myself. I hadn't yet tried it with a poorly filesystem! 

I might try at some point to see if that fsck's time could be saved if the filesystem's marked as cleanly dismounted, but I think safe's better for now.

**Comment by pgaskin** [comment]
No problem.
For me, it took fsck only 3 seconds, even for a very broken casper-rw
