### ISSUE TITLE
Ubuntu 14.04.3 LTS - 'upperdir' option for overlay mounting should be 'readwrite/upper'

### ISSUE THREAD

**Issue by rotoclabs** [davstott/ubuntu-usb-merge#4]
The existing version of ubuntu-usb-merge hasn't worked for me when I tried with Ubuntu 14.04.3 LTS workstation image. 

The casper-rw content is slightly different, and the overlay contents appear in a directory 'upper'.

```
# mount
/var/tmp/usblive/casper-rw on /var/tmp/usblive/readwrite type ext3 (rw)

# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0      3.9G  762M  3.0G  21% /var/tmp/usblive/readwrite

# ls readwrite/
format  lost+found  upper  work

# ls readwrite/upper
boot  cdrom  etc  home  lib  media  rofs  sbin  tmp  usr  var
```

So, the overlay mount works only with a slight modification to the original command. The upperdir option needs to be taken down a level inside

```
# mount none merged -o lowerdir=readonly,upperdir=readwrite/upper -t overlayfs
```

`

**Comment by davstott** [comment]
Thanks for the good description. I've just added some naïve support for that to the script and will test it as soon as I can, but it's committed as a speculative fix anyway
